require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe User::CommentsController, type: :controller do
  include Devise::TestHelpers

  let!(:user1) { create(:user) }
  let!(:question1) { create(:question, user: user1) }
  let!(:answer1) { create(:answer, user: user1, question: question1) }

  # This should return the minimal set of attributes required to create a valid
  # Answer. As you add validations to Answer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:comment, user:user1, answer:answer1)
  }

  let(:invalid_attributes) {
    attributes_for(:comment, rate:nil)
  }

  before do
    @request.env["devise.mapping"] = Devise.mappings[:user]
    sign_in user1
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Comment" do
        expect {
          post :create, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :comment => valid_attributes}
        }.to change(Comment, :count).by(1)
      end

      it "assigns a newly created comment as @comment" do
        post :create, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :comment => valid_attributes}
        expect(assigns(:comment)).to be_a(Comment)
        expect(assigns(:comment)).to be_persisted
      end

      it "redirects to the created comment" do
        post :create, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :comment => valid_attributes}
        expect(response).to have_http_status(200)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved comment as @comment" do
        post :create, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :comment => invalid_attributes}
        expect(assigns(:comment)).to be_a_new(Comment)
      end

      it "re-renders the 'new' template" do
        post :create, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :comment => invalid_attributes}
        expect(response).to have_http_status(200)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {body: 'NEW BODY'}
      }

      it "updates the requested comment" do
        comment = Comment.create! valid_attributes
        put :update, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :id => comment.to_param, :comment => new_attributes}
        comment.reload
        expect(assigns(:comment).body).to eq('NEW BODY')
      end

      it "assigns the requested comment as @comment" do
        comment = Comment.create! valid_attributes
        put :update, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :id => comment.to_param, :comment => valid_attributes}
        expect(assigns(:comment)).to eq(comment)
      end

      it "redirects to the comment" do
        comment = Comment.create! valid_attributes
        put :update, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :id => comment.to_param, :comment => valid_attributes}
        expect(response).to have_http_status(200)
      end
    end

    context "with invalid params" do
      it "assigns the comment as @comment" do
        comment = Comment.create! valid_attributes
        put :update, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :id => comment.to_param, :comment => invalid_attributes}
        expect(assigns(:comment)).to eq(comment)
      end

      it "re-renders the 'edit' template" do
        comment = Comment.create! valid_attributes
        put :update, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :id => comment.to_param, :comment => invalid_attributes}
        expect(response).to have_http_status(200)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested comment" do
      comment = Comment.create! valid_attributes
      expect {
        delete :destroy, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :id => comment.to_param}
      }.to change(Comment, :count).by(-1)
    end

    it "redirects to the comments list" do
      comment = Comment.create! valid_attributes
      delete :destroy, {format: :js, question_id:question1.to_param, answer_id:answer1.to_param, :id => comment.to_param}
      expect(response).to have_http_status(200)
    end
  end

end
